version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    volumes:
      - ./thai.sql:/docker-entrypoint-initdb.d/thai.sql
    ports:
      - "5432:5432"
